// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wira.Api.Data;

#nullable disable

namespace Wira.Api.Migrations
{
    [DbContext(typeof(WiraDbContext))]
    partial class WiraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wira.Api.Models.ArchivoAdjunto", b =>
                {
                    b.Property<int>("ArchivoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchivoID"));

                    b.Property<int>("EntidadID")
                        .HasColumnType("int");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PropuestaID")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TamañoBytes")
                        .HasColumnType("int");

                    b.Property<string>("TipoMime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArchivoID");

                    b.HasIndex("PropuestaID");

                    b.ToTable("ArchivosAdjuntos", t =>
                        {
                            t.HasCheckConstraint("CK_ArchivosAdjuntos_EntidadTipo", "[EntidadTipo] IN ('LICITACION', 'PROPUESTA')");
                        });
                });

            modelBuilder.Entity("Wira.Api.Models.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaID"));

                    b.Property<string>("ClaveRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Wira.Api.Models.CalificacionPostLicitacion", b =>
                {
                    b.Property<int>("CalificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalificacionID"));

                    b.Property<int?>("Calidad")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<int?>("Comunicacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("LicitacionID")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorID")
                        .HasColumnType("int");

                    b.Property<int?>("Puntualidad")
                        .HasColumnType("int");

                    b.HasKey("CalificacionID");

                    b.HasIndex("LicitacionID");

                    b.HasIndex("ProveedorID");

                    b.ToTable("CalificacionesPostLicitacion", t =>
                        {
                            t.HasCheckConstraint("CK_CalificacionPostLicitacion_Calidad", "[Calidad] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_CalificacionPostLicitacion_Comunicacion", "[Comunicacion] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_CalificacionPostLicitacion_Puntualidad", "[Puntualidad] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Wira.Api.Models.CriterioLicitacion", b =>
                {
                    b.Property<int>("CriterioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterioID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsExcluyente")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPuntuable")
                        .HasColumnType("bit");

                    b.Property<int>("LicitacionID")
                        .HasColumnType("int");

                    b.Property<bool?>("MayorMejor")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("ValorRequeridoBooleano")
                        .HasColumnType("bit");

                    b.HasKey("CriterioID");

                    b.HasIndex("LicitacionID");

                    b.ToTable("CriteriosLicitacion", t =>
                        {
                            t.HasCheckConstraint("CK_CriterioLicitacion_MayorMejorAplicable", "[Tipo] = 1 OR [MayorMejor] IS NULL");

                            t.HasCheckConstraint("CK_CriterioLicitacion_MayorMejorRequerido", "[Tipo] <> 1 OR [MayorMejor] IS NOT NULL");

                            t.HasCheckConstraint("CK_CriterioLicitacion_Tipo", "[Tipo] IN (1,2,3,4)");

                            t.HasCheckConstraint("CK_CriterioLicitacion_ValorBooleanoAplicable", "[Tipo] = 2 OR [ValorRequeridoBooleano] IS NULL");

                            t.HasCheckConstraint("CK_CriterioLicitacion_ValorBooleanoRequerido", "[Tipo] <> 2 OR [EsPuntuable] = 0 OR [ValorRequeridoBooleano] IS NOT NULL");

                            t.HasCheckConstraint("CK_CriterioLicitacion_Valores", "[ValorMinimo] IS NULL OR [ValorMaximo] IS NULL OR [ValorMinimo] <= [ValorMaximo]");
                        });
                });

            modelBuilder.Entity("Wira.Api.Models.CriterioOpcion", b =>
                {
                    b.Property<int>("OpcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionID"));

                    b.Property<int>("CriterioID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("Puntaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OpcionID");

                    b.HasIndex("CriterioID", "Valor")
                        .IsUnique();

                    b.ToTable("CriteriosOpciones");
                });

            modelBuilder.Entity("Wira.Api.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RubroID")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoEmpresa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpresaID");

                    b.HasIndex("CUIT")
                        .IsUnique()
                        .HasDatabaseName("UX_Empresas_CUIT");

                    b.HasIndex("RubroID");

                    b.ToTable("Empresas", t =>
                        {
                            t.HasCheckConstraint("CK_Empresas_TipoEmpresa", "[TipoEmpresa] IN ('MINERA', 'PROVEEDOR')");
                        });
                });

            modelBuilder.Entity("Wira.Api.Models.EstadoLicitacion", b =>
                {
                    b.Property<int>("EstadoLicitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoLicitacionID"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoLicitacionID");

                    b.HasIndex("NombreEstado")
                        .IsUnique();

                    b.ToTable("EstadosLicitacion");
                });

            modelBuilder.Entity("Wira.Api.Models.EstadoPropuesta", b =>
                {
                    b.Property<int>("EstadoPropuestaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoPropuestaID"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoPropuestaID");

                    b.HasIndex("NombreEstado")
                        .IsUnique();

                    b.ToTable("EstadosPropuesta");
                });

            modelBuilder.Entity("Wira.Api.Models.HistorialProveedorLicitacion", b =>
                {
                    b.Property<int>("HistorialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialID"));

                    b.Property<DateTime?>("FechaGanador")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaParticipacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool?>("Ganador")
                        .HasColumnType("bit");

                    b.Property<int>("LicitacionID")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ProveedorID")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HistorialID");

                    b.HasIndex("LicitacionID");

                    b.HasIndex("ProveedorID");

                    b.ToTable("HistorialProveedorLicitacion");
                });

            modelBuilder.Entity("Wira.Api.Models.Licitacion", b =>
                {
                    b.Property<int>("LicitacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicitacionID"));

                    b.Property<int?>("ArchivoID")
                        .HasColumnType("int");

                    b.Property<string>("Condiciones")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EstadoLicitacionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MineraID")
                        .HasColumnType("int");

                    b.Property<int>("MonedaID")
                        .HasColumnType("int");

                    b.Property<decimal?>("PresupuestoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProyectoMineroID")
                        .HasColumnType("int");

                    b.Property<int>("RubroID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LicitacionID");

                    b.HasIndex("ArchivoID");

                    b.HasIndex("EstadoLicitacionID");

                    b.HasIndex("MineraID");

                    b.HasIndex("MonedaID");

                    b.HasIndex("ProyectoMineroID");

                    b.HasIndex("RubroID");

                    b.ToTable("Licitaciones");
                });

            modelBuilder.Entity("Wira.Api.Models.Moneda", b =>
                {
                    b.Property<int>("MonedaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonedaID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Simbolo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MonedaID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("Wira.Api.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionID"));

                    b.Property<int?>("EntidadID")
                        .HasColumnType("int");

                    b.Property<string>("EntidadTipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NotificacionID");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Wira.Api.Models.NotificacionUsuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("NotificacionID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("FechaLeido")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("UsuarioID", "NotificacionID");

                    b.HasIndex("NotificacionID");

                    b.ToTable("NotificacionesUsuarios");
                });

            modelBuilder.Entity("Wira.Api.Models.Propuesta", b =>
                {
                    b.Property<int>("PropuestaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropuestaID"));

                    b.Property<decimal?>("CalificacionFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("CumpleRequisitos")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EstadoPropuestaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("LicitacionID")
                        .HasColumnType("int");

                    b.Property<int>("MonedaID")
                        .HasColumnType("int");

                    b.Property<decimal>("PresupuestoOfrecido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorID")
                        .HasColumnType("int");

                    b.HasKey("PropuestaID");

                    b.HasIndex("EstadoPropuestaID");

                    b.HasIndex("LicitacionID");

                    b.HasIndex("MonedaID");

                    b.HasIndex("ProveedorID");

                    b.ToTable("Propuestas");
                });

            modelBuilder.Entity("Wira.Api.Models.ProyectoMinero", b =>
                {
                    b.Property<int>("ProyectoMineroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoMineroID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MineraID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProyectoMineroID");

                    b.HasIndex("MineraID");

                    b.ToTable("ProyectosMineros");
                });

            modelBuilder.Entity("Wira.Api.Models.RespuestaCriterioLicitacion", b =>
                {
                    b.Property<int>("RespuestaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespuestaID"));

                    b.Property<int>("CriterioID")
                        .HasColumnType("int");

                    b.Property<int?>("CriterioOpcionID")
                        .HasColumnType("int");

                    b.Property<int>("PropuestaID")
                        .HasColumnType("int");

                    b.Property<bool?>("ValorBooleano")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValorNumerico")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValorProveedor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RespuestaID");

                    b.HasIndex("CriterioID");

                    b.HasIndex("CriterioOpcionID");

                    b.HasIndex("PropuestaID");

                    b.ToTable("RespuestasCriteriosLicitacion");
                });

            modelBuilder.Entity("Wira.Api.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Wira.Api.Models.Rubro", b =>
                {
                    b.Property<int>("RubroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubroID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RubroID");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("Wira.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AprobadoPorUsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaVencimientoTokenRecuperacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoTokenVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TokenRecuperacionPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TokenVerificacionEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("ValidadoEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("UsuarioID");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Wira.Api.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RolID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UsuarioID", "RolID");

                    b.HasIndex("RolID");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("Wira.Api.Models.ArchivoAdjunto", b =>
                {
                    b.HasOne("Wira.Api.Models.Propuesta", "Propuesta")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("PropuestaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("Wira.Api.Models.Auditoria", b =>
                {
                    b.HasOne("Wira.Api.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wira.Api.Models.CalificacionPostLicitacion", b =>
                {
                    b.HasOne("Wira.Api.Models.Licitacion", "Licitacion")
                        .WithMany("CalificacionesPost")
                        .HasForeignKey("LicitacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Empresa", "Proveedor")
                        .WithMany("CalificacionesPost")
                        .HasForeignKey("ProveedorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Licitacion");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Wira.Api.Models.CriterioLicitacion", b =>
                {
                    b.HasOne("Wira.Api.Models.Licitacion", "Licitacion")
                        .WithMany("CriteriosLicitacion")
                        .HasForeignKey("LicitacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Licitacion");
                });

            modelBuilder.Entity("Wira.Api.Models.CriterioOpcion", b =>
                {
                    b.HasOne("Wira.Api.Models.CriterioLicitacion", "Criterio")
                        .WithMany("Opciones")
                        .HasForeignKey("CriterioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterio");
                });

            modelBuilder.Entity("Wira.Api.Models.Empresa", b =>
                {
                    b.HasOne("Wira.Api.Models.Rubro", "Rubro")
                        .WithMany("Proveedores")
                        .HasForeignKey("RubroID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Wira.Api.Models.HistorialProveedorLicitacion", b =>
                {
                    b.HasOne("Wira.Api.Models.Licitacion", "Licitacion")
                        .WithMany("HistorialesProveedor")
                        .HasForeignKey("LicitacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Empresa", "Proveedor")
                        .WithMany("HistorialesProveedor")
                        .HasForeignKey("ProveedorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Licitacion");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Wira.Api.Models.Licitacion", b =>
                {
                    b.HasOne("Wira.Api.Models.ArchivoAdjunto", "ArchivoAdjunto")
                        .WithMany()
                        .HasForeignKey("ArchivoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wira.Api.Models.EstadoLicitacion", "EstadoLicitacion")
                        .WithMany("Licitaciones")
                        .HasForeignKey("EstadoLicitacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Empresa", "Minera")
                        .WithMany("Licitaciones")
                        .HasForeignKey("MineraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Moneda", "Moneda")
                        .WithMany("Licitaciones")
                        .HasForeignKey("MonedaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.ProyectoMinero", "ProyectoMinero")
                        .WithMany("Licitaciones")
                        .HasForeignKey("ProyectoMineroID");

                    b.HasOne("Wira.Api.Models.Rubro", "Rubro")
                        .WithMany("Licitaciones")
                        .HasForeignKey("RubroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArchivoAdjunto");

                    b.Navigation("EstadoLicitacion");

                    b.Navigation("Minera");

                    b.Navigation("Moneda");

                    b.Navigation("ProyectoMinero");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Wira.Api.Models.NotificacionUsuario", b =>
                {
                    b.HasOne("Wira.Api.Models.Notificacion", "Notificacion")
                        .WithMany("NotificacionesUsuarios")
                        .HasForeignKey("NotificacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Usuario", "Usuario")
                        .WithMany("NotificacionesUsuarios")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wira.Api.Models.Propuesta", b =>
                {
                    b.HasOne("Wira.Api.Models.EstadoPropuesta", "EstadoPropuesta")
                        .WithMany("Propuestas")
                        .HasForeignKey("EstadoPropuestaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Licitacion", "Licitacion")
                        .WithMany("Propuestas")
                        .HasForeignKey("LicitacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Moneda", "Moneda")
                        .WithMany("Propuestas")
                        .HasForeignKey("MonedaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Empresa", "Proveedor")
                        .WithMany("Propuestas")
                        .HasForeignKey("ProveedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoPropuesta");

                    b.Navigation("Licitacion");

                    b.Navigation("Moneda");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Wira.Api.Models.ProyectoMinero", b =>
                {
                    b.HasOne("Wira.Api.Models.Empresa", "Minera")
                        .WithMany("ProyectosMineros")
                        .HasForeignKey("MineraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Minera");
                });

            modelBuilder.Entity("Wira.Api.Models.RespuestaCriterioLicitacion", b =>
                {
                    b.HasOne("Wira.Api.Models.CriterioLicitacion", "Criterio")
                        .WithMany("RespuestasCriterios")
                        .HasForeignKey("CriterioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.CriterioOpcion", "OpcionSeleccionada")
                        .WithMany()
                        .HasForeignKey("CriterioOpcionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wira.Api.Models.Propuesta", "Propuesta")
                        .WithMany("RespuestasCriterios")
                        .HasForeignKey("PropuestaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criterio");

                    b.Navigation("OpcionSeleccionada");

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("Wira.Api.Models.Usuario", b =>
                {
                    b.HasOne("Wira.Api.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Wira.Api.Models.UsuarioRol", b =>
                {
                    b.HasOne("Wira.Api.Models.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wira.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wira.Api.Models.CriterioLicitacion", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("RespuestasCriterios");
                });

            modelBuilder.Entity("Wira.Api.Models.Empresa", b =>
                {
                    b.Navigation("CalificacionesPost");

                    b.Navigation("HistorialesProveedor");

                    b.Navigation("Licitaciones");

                    b.Navigation("Propuestas");

                    b.Navigation("ProyectosMineros");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Wira.Api.Models.EstadoLicitacion", b =>
                {
                    b.Navigation("Licitaciones");
                });

            modelBuilder.Entity("Wira.Api.Models.EstadoPropuesta", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("Wira.Api.Models.Licitacion", b =>
                {
                    b.Navigation("CalificacionesPost");

                    b.Navigation("CriteriosLicitacion");

                    b.Navigation("HistorialesProveedor");

                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("Wira.Api.Models.Moneda", b =>
                {
                    b.Navigation("Licitaciones");

                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("Wira.Api.Models.Notificacion", b =>
                {
                    b.Navigation("NotificacionesUsuarios");
                });

            modelBuilder.Entity("Wira.Api.Models.Propuesta", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("RespuestasCriterios");
                });

            modelBuilder.Entity("Wira.Api.Models.ProyectoMinero", b =>
                {
                    b.Navigation("Licitaciones");
                });

            modelBuilder.Entity("Wira.Api.Models.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Wira.Api.Models.Rubro", b =>
                {
                    b.Navigation("Licitaciones");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Wira.Api.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("NotificacionesUsuarios");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
